import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

// Helper to recursively list files in a directory
function getFilesRecursive(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      getFilesRecursive(filePath, fileList);
    } else {
      fileList.push(filePath);
    }
  }
  return fileList;
}

const assets = {};

// 1. Scan scripts directory
const scriptsDir = path.join(projectRoot, 'scripts');
if (fs.existsSync(scriptsDir)) {
  const files = getFilesRecursive(scriptsDir);
  for (const file of files) {
    const relPath = path.relative(projectRoot, file).replace(/\\/g, '/');
    // Ignore build/release scripts that are not run on target machines
    if (relPath === 'scripts/release.js' || relPath === 'scripts/build-assets.js') {
      continue;
    }
    const content = fs.readFileSync(file);
    assets[relPath] = content.toString('base64');
  }
}

// 2. Add config and schema files
const configFiles = ['ziptie.default.config.json', 'ziptie.schema.json'];
for (const confFile of configFiles) {
  const filePath = path.join(projectRoot, confFile);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath);
    assets[confFile] = content.toString('base64');
  }
}

// Generate the output TS file content
const outputDir = path.join(projectRoot, 'src');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const outputContent = `// This file is auto-generated by scripts/build-assets.js. Do not edit manually.
export const EMBEDDED_ASSETS: Record<string, string> = {
${Object.entries(assets)
  .map(([key, val]) => `  ${JSON.stringify(key)}: ${JSON.stringify(val)}`)
  .join(',\n')}
};
`;

fs.writeFileSync(path.join(outputDir, 'assets.ts'), outputContent, 'utf8');
console.log(`Successfully generated src/assets.ts with ${Object.keys(assets).length} embedded assets!`);
